### ISSUE TITLE
[quick-prayer-preview] requesting ownership transfer

### ISSUE THREAD

**Issue by rdutta** [Hydrox6/external-plugins#117]
Unless you are still maintaining it, in which case feel free to close this. Just need a sign of life, since it's been 4 years since it was updated 👍

No rush on the PR.

**Comment by Enriath** [comment]
I'm not really keen on transferring ownership of any of my plugins, at any point. I have seen too many plugins get taken over and warped into something that, while they may end up with more features, become much more frail and bloated, and a shadow of their former self. I am keen to not let that happen to what I wrote.

It's been 4 years because the plugin hasn't needed any changes since I wrote it. As it stands, it works perfectly fine, and that was the plan. Don't need to update something when it works as advertised.
I do really like some of your suggestions that you've put in the PR, and at some point I'll end up looking at them.
