### ISSUE TITLE
[Subtle Virtual Levels] Experience left until next virtual level

### ISSUE THREAD

**Issue by Hjaldr** [Hydrox6/external-plugins#127]
This issue is for the external plugin: Subtle Virtual Levels
Plugin version: 1.1
The plugin does not show experience until the next virtual level, unlike the generic plugin. While the visualization is better, not having the experience remaining shown in the hover-over information for a post-99 skill makes it less usable for tracking milestones past 99.

**Comment by Enriath** [comment]
Subtle Virtual Levels wasn't ever designed to do anything you mentioned here, as it's meant to do one thing and do it well (or at least well enough). It just adds the little darker box with the virtual level in it. No tooltip, no level tracking, by design. In this screenshot, it's the just that 109.
![image](https://github.com/user-attachments/assets/fbf22122-3416-4172-8494-6381b8129a7d)
Going forward, it won't get support for tooltips, also because I already have a plugin that does what you want.

Better Skill Tooltips is another plugin I made to make the tooltips better. It supports showing virtual level experience like the core Virtual Levels plugin, but only changes the tooltip. It also has a nice way to display goals (which it pulls from the vanilla goals), and given the vanilla goals support levels past 99 it could be quite useful for you.

Sub-99 skill with no goal (also the same on vanilla)
![image](https://github.com/user-attachments/assets/13989651-815b-4082-b243-b3c6641ddbaf)

\>= 99 skill with no goal, with the `Show virtual level info` option enabled
![image](https://github.com/user-attachments/assets/58190df2-c0fc-4a96-9b13-36294cf8e8db)

\>= 99 skill with a goal set, with all options enabled
![image](https://github.com/user-attachments/assets/b18c507e-81eb-4cc0-af23-b554dba92303)

**Comment by Hjaldr** [comment]
I didn't know about the other plugin. I just figured because the vanilla virtual levels plugin lacked an option to hide virtual levels but still show experience tooltips, it was either/or, but this solves it, thanks!
