### ISSUE TITLE
[Transmogrification] Trailblazer t2-t3 top missing

### ISSUE THREAD

**Issue by MarbleTurtle** [Hydrox6/external-plugins#28]
When searching for t2 or t3 trailblazer top are not present as options.
![image](https://user-images.githubusercontent.com/60723971/105882697-cfcff400-5fba-11eb-9b55-f52a706fa0f7.png)

**Comment by Hydrox6** [comment]
So how the search works is it pulls data from ItemManager, which has data scraped from the wiki periodically. For whatever reason, it seems it failed to scrape the T2 and T3 trailblazer top. I don't really think there's anything I can do about this; hardcoding extra items into the search is really jank, and since it failed here, the core Item Stats plugin will also be broken. Abex has mentioned there is currently (at time of writing) an issue with the scraper, so hopefully that gets fixed soon.
