### ISSUE TITLE
[Transmogrification] Donate button and save feature 

### ISSUE THREAD

**Issue by bsr5088** [Hydrox6/external-plugins#35]
I absolutely love this pluggin and wanted to donate a few bucks your way, can you add a donate button to the page on github maybe? 

Also, any idea when saving the presets will return? (if you can save them currently im not sure how as my changes revert when i login)

**Comment by Hydrox6** [comment]
Glad to hear you like it so much! I'm very proud of how the UI turned out, and barring some features I've got planned, I'm extremely happy with it. I need to have a look at how GitHub's Sponsor stuff works and set something up, but I'll do that shortly.

As for save, no functionality went away. The issue with Save and Delete is they didn't do anything; editing a preset already saves it automatically. The buttons exist from a time in development where I thought I'd want manual saving, and the eventual only use for them was to move a preset to another slot.  All delete did was reset the preset back to the default state, which is pretty trivial to do manually either way. It was subsequently found that save did not work in the slightest, and so given that both buttons did basically nothing, I decided to remove them.

With issue #29, there's an interesting idea that cannot work in the current system: an IF This Then That (IFTTT) style system for dynamically swapping items. With only 4 slots to work with, it's basically unusable, removing any granularity that you may want, and even without it 4 slots just isn't enough to experiment with. For that, I've started work on expanding the preset system to support an extremely large amount (though I'm likely to cap it, it'll still be orders of magnitude higher). The UI is in place, though I'm having issues with the development; Dependency Injection is weird and somehow I've accidentally made a circle. Either way, it's in this UI that the save and delete buttons will finally have a purpose, and though they're not implemented yet, I hope I can fix this circular dependency issue before I go mad.

**Comment by Hydrox6** [comment]
I've added the link. Spent way too long trying to find a suitable background :d

**Comment by Hydrox6** [comment]
So I just want to update this: turns out saving *was* actually broken. I really don't know how I missed this, as I could have sworn I made autosaving work at some point during development. v1.1.3 has autosaving when logging out, hopping, or turning off the plugin, which should cover it for the time being.

**Comment by bsr5088** [comment]
Awesome dude, glad you caught it. Looks like it’s working now.
