### ISSUE TITLE
[Plank Sack] Counter goes to zero at every mahogany homes interaction

### ISSUE THREAD

**Issue by mika1369** [Hydrox6/external-plugins#45]
This issue is for the external plugin: {Plank Sack}

I have been using the plank sack plugin while doing mahogany homes, and every time i have no planks in my inventory, and do a repair, instead of the counter going down by the two or so planks that i used, it goes straight to zero.

**Comment by Hydrox6** [comment]
So I saw this and thought "That can't be right, I spent ages testing that and making sure it works"

Then I read the code and realised that while refactoring the function that saves the config, I royally screwed up and started setting the amount of planks to `-1` instead of removing `1`.

Thanks for bringing this up, it will be fixed in the 1.1 release
