### ISSUE TITLE
[Plank Sack] Amount desyncs from mahogany homes actions

### ISSUE THREAD

**Issue by itssapir** [Hydrox6/external-plugins#46]
This issue is for the external plugin: Plank Sack

I observed 2 situations where this happens -
 * Repair action while there are planks in both the sack and inventory, this uses a plank from the inventory, but the plank sack
    counter still decreases.
 * I think some other actions also create a similar de-sync when, but couldn't pinpoint the which ones

**Comment by Hydrox6** [comment]
So when I implemented the interface-less repair stuff, I forgot to add the extra checks needed to make sure it was actually pulling from the sack. I've fixed this for 1.2, which should be available shortly (I close issues when the fix is merged)

As for the desync, there's always going to be some, due to the nature of how the data is being tracked. I noticed earlier that lag can cause it to desync, and there's not really a way around that without massive overengineering. However, if you can find a consistent way to desync the counter, please do make a new issue with as much information as possible and precise recreation steps.
