### ISSUE TITLE
[Shattered Relic XP] Overlay not showing

### ISSUE THREAD

**Issue by Not2Day1024** [Hydrox6/external-plugins#79]
This issue is for the external plugin: Shattered Relic XP
Plugin version: 1.1

Not sure what relevant info you need, but I noticed I wasn't getting tooltips or set effect icons in my buff bar.

**Comment by Enriath** [comment]
1.1 is not a valid version

**Comment by Not2Day1024** [comment]
![v](https://user-images.githubusercontent.com/66974614/155363953-9ab474fe-554e-47ea-a303-2accdd95075c.png)

idk what you want from me, where does it list version number?

**Comment by Enriath** [comment]
In the plugin hub itself

**Comment by Not2Day1024** [comment]
idk, it says the same thing there. i understand this is a free plugin, and i don't need to use it, but i was just trying to get it to work. sorry if you are busy atm

**Comment by Enriath** [comment]
Considering I spent the last few hours fixing things you're claiming are broken, and you can't even get the version number that you're using to put in the template, there's not much I can do about it

**Comment by Not2Day1024** [comment]
not claiming anything. i was just trying to use the plugin. never said anything was broken, i actually assumed i did something wrong. mb for asking for help

**Comment by Enriath** [comment]
then you probably did do something wrong

either way, this is an issue tracker, not a support forum. This is a place for bug reports or feature requests.

**Comment by Not2Day1024** [comment]
i was hoping for a discord link but you provide no info in the readme :( didn't wanna bother the dev, but i guess nobody is available to help you.

you are being purposefully obtuse about the issue because of a version number. i said 1.1 and provided picture of it. i don't code and just play a 20 year old game. if you don't want the plugin to work for some people, idc. i thought i was helping by giving you a bug report

**Comment by Enriath** [comment]
It's very simple:
I ask for a version number so I know what version you're running. This is because multiple people have submitted bug reports in the past that I've already fixed. It's not being purposely obtuse when I ask for something incredibly simple to help the process.

Not only did you give garbage information, you might as well have just put anything for the version number, and the outcome would have been the same. If you're not going to submit accurate data for something so simple, how do I even know what you're saying for the rest of the issue is accurate?

A bug report that says "It doesn't work" with a bad version number is pretty much useless, tbh.

As for Discord, I'm accurate in the RuneLite server, where I'm alright with questions about my plugins outside of the support channel. Basically every hub dev can be found in there, and only the really big plugins have their own servers (e.g. Quest Helper, HD)

Either way, give accurate data. Most devs won't say it to your face, but they appreciate it when you follow their reporting instructions; unless you're planning to debug, fix, and PR it yourself, they're the ones who have to figure out why something's broken, and a lot of problems can be difficult to pin down.

**Comment by Not2Day1024** [comment]
except that it's not very simple to people who don't use these tools every day. it's hard to remember what it's like before you learn a skill, so you think this is all elementary. nobody is expecting a discord community of 1k+ members (especially if this is how you act), but if you provided that contact info in the readme, i could have known that.
in my first comment i even state that i do not know what information is relevant, so being purposefully obtuse is in reference to the version number. if i, someone who doesn't even know what info you would need, calls version 1.10 as 1.1 because they do not understand, then you are just not being helpful (which is your right, this is YOUR free plugin).
i understand problems can be difficult to track down, but closing a legitimate bug report without investigating further probably doesn't help. either way, its just a free plugin for a free program in a limited-time game mode of a 20 year old pixel clicking game. i'll live without it.
